# Generated by Django 5.2.7 on 2025-10-18 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transformation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit', models.CharField(max_length=100)),
                ('quantite_disponible', models.FloatField()),
                ('unite_mesure', models.CharField(choices=[('KG', 'Kg'), ('TONNE', 'Tonne'), ('SACHET', 'Sachet'), ('BOITE', 'Boite')], max_length=10)),
                ('date_mise_a_jour', models.DateField()),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transformation.transformation')),
            ],
        ),
    ]
