# Generated by Django 5.2.7 on 2025-12-09 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
        ('vente', '0002_client_prenom'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change', models.FloatField(help_text='Quantité modifiée (négatif pour sortie, positif pour entrée)')),
                ('reason', models.CharField(choices=[('VENTE', 'Vente'), ('RESTORE', 'Restauration'), ('AJUST', 'Ajustement'), ('MODIF', 'Modification')], default='VENTE', max_length=20)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='stock.stock')),
                ('vente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vente.vente')),
            ],
        ),
    ]
