# Generated by Django 5.2.7 on 2025-10-18 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('superficie', models.FloatField()),
                ('adresse', models.CharField(verbose_name=50)),
                ('producteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producteurs.producteur')),
            ],
        ),
        migrations.CreateModel(
            name='Recolte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fruit', models.CharField(max_length=50)),
                ('quantite', models.FloatField()),
                ('date_recolte', models.DateField()),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producteurs.parcelle')),
                ('producteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producteurs.producteur')),
            ],
        ),
    ]
