# Generated by Django 5.2.7 on 2025-12-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producteurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcelle',
            name='adresse',
            field=models.CharField(max_length=50),
        ),
    ]
