# Generated by Django 5.2.7 on 2025-10-18 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producteurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_lot', models.CharField(max_length=50)),
                ('etape', models.CharField(choices=[('LYOPHILISATION', 'Lyophilisation'), ('CONDITIONNEMENT', 'Conditionnement'), ('STOCKE', 'Stocké')], max_length=20)),
                ('quantite_depart', models.FloatField()),
                ('quantite_finale', models.FloatField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('recolte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producteurs.recolte')),
            ],
        ),
    ]
